build:
  image: golang:1.5
  environment:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux
    - GOARCH=amd64
    - CGO_ENABLED=0
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-pypi
    when:
      branch: master

plugin:
  name: NPM
  desc: Publish a package to the Python package index.
  type: publish
  image: plugins/drone-pypi
  labels:
    - publish
    - python
